<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.HU-SHD.it</groupId>
    <artifactId>basic-download-test</artifactId>
    <version>1.0</version>
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.HU-SHD</groupId>
                <artifactId>resumble_download_maven_plugin</artifactId>
                <version>@project.version@</version> <!-- 注意必须是 @project.version@ -->
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals><goal>download</goal></goals>
                        <configuration>
                            <url>https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/3.9.9/maven-core-3.9.9.jar</url>
                            <outputDirectory>${project.build.directory}/downloads</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>